import {spawnSync} from 'node:child_process';import fs from 'node:fs';import path from 'node:path';import {randomBytes} from 'node:crypto';import readline from 'node:readline/promises';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');process.chdir(root);const cli=path.join(root,'node_modules/wrangler/bin/wrangler.js');const run=(args,options={})=>{const r=spawnSync(process.execPath,[cli,...args],{stdio:'inherit',...options});if(r.status!==0)throw new Error('Команда не завершилась: wrangler '+args.slice(0,2).join(' '));return r;};const rl=readline.createInterface({input:process.stdin,output:process.stdout});
try{console.log('Публикация HTML-сайта и сервера в вашем аккаунте Cloudflare.');const configPath=path.join(root,'wrangler.jsonc');const c=JSON.parse(fs.readFileSync(configPath,'utf8'));if(c.d1_databases[0].database_id==='00000000-0000-0000-0000-000000000000'){
const name=(await rl.question('Уникальное имя проекта (латиницей, например cafe-almaty-menu): ')).trim();if(!/^[a-z][a-z0-9-]{2,50}$/.test(name))throw new Error('Нужно имя из строчных латинских букв, цифр и дефисов.');c.name=name;c.d1_databases[0].database_name=name+'-db';run(['login']);const out=run(['d1','create',name+'-db'],{encoding:'utf8',stdio:['inherit','pipe','inherit']}).stdout;process.stdout.write(out);const match=out.match(/(?:"database_id"\s*:\s*"|database_id\s*=\s*")([a-f0-9-]{36})"/);if(!match)throw new Error('Впишите database_id из ответа Cloudflare в wrangler.jsonc и запустите публикацию снова.');c.d1_databases[0].database_id=match[1];fs.writeFileSync(configPath,JSON.stringify(c,null,2)+'\n');}
run(['d1','migrations','apply','DB','--remote']);run(['deploy']);
if((await rl.question('Настроить секреты при первом запуске? (да/нет; при обновлении — нет): ')).trim().toLowerCase()==='да'){
const password=randomBytes(20).toString('hex'),secret=randomBytes(32).toString('hex');run(['secret','put','ADMIN_PASSWORD'],{input:password+'\n',stdio:['pipe','inherit','inherit']});run(['secret','put','SESSION_SECRET'],{input:secret+'\n',stdio:['pipe','inherit','inherit']});console.log('\nСОХРАНИТЕ ПАРОЛЬ АДМИНИСТРАТОРА В МЕНЕДЖЕРЕ ПАРОЛЕЙ:\n'+password+'\n');console.log('Введите токен бота заказов в защищённом запросе Wrangler:');run(['secret','put','ORDERS_BOT_TOKEN']);console.log('Введите токен отдельного бота отзывов:');run(['secret','put','ADMIN_BOT_TOKEN']);}
console.log('Откройте опубликованный адрес /admin. Заполните меню, создайте столы, сохраните ID сотрудников и подключите ботов. После проверки включите приём заказов.');
}catch(e){console.error(e.message);process.exitCode=1;}finally{rl.close();}
