export class Fault extends Error { constructor(message,status=409){super(message);this.status=status;} }
export const now=()=>Math.floor(Date.now()/1000);
export const token=(bytes=32)=>Array.from(crypto.getRandomValues(new Uint8Array(bytes)),b=>b.toString(16).padStart(2,'0')).join('');
export const uid=()=>crypto.randomUUID();
export const sha=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,'0')).join('');
export async function sign(env,s){if(!env.SESSION_SECRET||env.SESSION_SECRET.length<32)throw new Fault('Сайт ещё не настроен.',503);const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(env.SESSION_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);return Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,'0')).join('');}
export function equal(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
export function text(x,max=300){if(typeof x!=='string'||x.length>max)throw new Fault('Проверьте длину текстового поля.',400);return x.trim();}
export const money=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(n/100)+' ₸';
export function cookie(req,name){const found=(req.headers.get('cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='));return found?found.slice(name.length+1):'';}
export function cookieValue(req,name,value,age){return `${name}=${value}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${age}${new URL(req.url).protocol==='https:'?'; Secure':''}`;}
export function query(env,sql,...args){return env.DB.prepare(sql).bind(...args);}
export async function rate(env,key,max,seconds){const t=now(),k=await sha(key+':'+Math.floor(t/seconds));const r=await query(env,'INSERT INTO limits (key,hits,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET hits=hits+1 RETURNING hits',k,t+seconds*2).first();if(r.hits>max)throw new Fault('Слишком много попыток. Подождите немного.',429);}
export async function lock(env,key,seconds){const t=now(),v=token(12);const row=await query(env,'INSERT INTO locks (key,until_at,token) VALUES (?,?,?) ON CONFLICT(key) DO UPDATE SET until_at=excluded.until_at,token=excluded.token WHERE locks.until_at<=? RETURNING token',key,t+seconds,v,t).first();return row?.token===v?v:null;}
export async function unlock(env,key,t){await query(env,'UPDATE locks SET until_at=0 WHERE key=? AND token=?',key,t).run();}
export const defaults={name:'Dastarhan',service_bps:1000,hours:6,enabled:false,kaspi_url:'',chat_id:'',staff_ids:[],cashier_ids:[],admin_chat_id:'',admin_ids:[],orders_connected:false,admin_connected:false,items:[{id:1,name:'Плов по-домашнему',category:'Горячее',price:360000,weight:'350 г',description:'Рис, говядина, морковь, нут и запечённый чеснок',available:true,image:'/assets/plov.webp'},{id:2,name:'Манты с говядиной',category:'Горячее',price:320000,weight:'5 шт.',description:'Тонкое тесто, рубленая говядина и лук',available:true,image:''},{id:3,name:'Домашний лагман',category:'Горячее',price:340000,weight:'400 г',description:'Тянутая лапша, говядина и свежие овощи',available:true,image:''},{id:4,name:'Ачичук',category:'Закуски',price:160000,weight:'200 г',description:'Томаты, лук и базилик',available:true,image:''},{id:5,name:'Самса из тандыра',category:'Закуски',price:90000,weight:'1 шт.',description:'Хрустящая корочка и сочная говядина',available:true,image:''},{id:6,name:'Чай по-казахски',category:'Напитки',price:180000,weight:'800 мл',description:'Чёрный чай с молоком в большом чайнике',available:true,image:''}],sample_menu:true};
export async function config(env){const r=await query(env,'SELECT * FROM config WHERE id=1').first();return r?{...JSON.parse(r.data),version:r.version}:{...structuredClone(defaults),version:-1};}
export async function saveConfig(env,c,version){const {version:_,...data}=c;const res=version===-1?await query(env,'INSERT OR IGNORE INTO config(id,version,data) VALUES (1,0,?)',JSON.stringify(data)).run():await query(env,'UPDATE config SET data=?,version=version+1 WHERE id=1 AND version=?',JSON.stringify(data),version).run();if(res.meta.changes!==1)throw new Fault('Настройки изменились в другом окне. Обновите страницу.');return {...data,version:version+1};}
export function validateConfig(p,old,env){const c={...old};c.name=text(p.name,80);if(!c.name)throw new Fault('Укажите название.',400);c.service_bps=p.service_bps;if(!Number.isInteger(c.service_bps)||c.service_bps<0||c.service_bps>3000)throw new Fault('Обслуживание: от 0 до 30%.',400);c.hours=p.hours;if(!Number.isInteger(c.hours)||c.hours<1||c.hours>24)throw new Fault('Срок доступа: от 1 до 24 часов.',400);for(const k of ['staff_ids','cashier_ids','admin_ids']){if(!Array.isArray(p[k])||p[k].length>100||p[k].some(x=>!/^\d{1,20}$/.test(x)))throw new Fault('Проверьте Telegram ID сотрудников.',400);c[k]=[...new Set(p[k].map(String))];}c.chat_id=text(p.chat_id,30);c.admin_chat_id=text(p.admin_chat_id,30);if(c.chat_id&&!/^-\d{1,20}$/.test(c.chat_id))throw new Fault('Для заказов нужен отрицательный ID группы.',400);if(c.admin_chat_id&&!/^\d{1,20}$/.test(c.admin_chat_id))throw new Fault('Для отзывов нужен ID личного чата.',400);c.kaspi_url=text(p.kaspi_url,500);if(c.kaspi_url){let u;try{u=new URL(c.kaspi_url);}catch{throw new Fault('Неверная ссылка Kaspi.',400);}if(u.protocol!=='https:'||u.hostname!=='kaspi.kz'||u.username||u.password)throw new Fault('Нужна HTTPS-ссылка на kaspi.kz.',400);}
if(!Array.isArray(p.items)||p.items.length>150)throw new Fault('Не больше 150 блюд.',400);const ids=new Set();c.items=p.items.map(i=>{if(!Number.isSafeInteger(i.id)||i.id<1||ids.has(i.id)||!Number.isInteger(i.price)||i.price<1||i.price>999990000)throw new Fault('Проверьте ID и цены блюд.',400);ids.add(i.id);const image=text(i.image,1000);if(image&&!/^\/assets\/[a-zA-Z0-9_.-]+$/.test(image)){let u;try{u=new URL(image);}catch{throw new Fault('Неверный адрес фотографии.',400);}if(u.protocol!=='https:')throw new Fault('Фотографии должны использовать HTTPS.',400);}return {id:i.id,name:text(i.name,100),category:text(i.category,60)||'Меню',description:text(i.description,600),weight:text(i.weight,60),price:i.price,available:!!i.available,image};});if(c.items.some(i=>!i.name))throw new Fault('У блюда должно быть название.',400);c.sample_menu=!!p.sample_menu;
if(c.chat_id!==old.chat_id)c.orders_connected=false;if(c.admin_chat_id!==old.admin_chat_id)c.admin_connected=false;c.enabled=!!p.enabled;if(c.enabled&&(!env.ORDERS_BOT_TOKEN||!c.chat_id||!c.cashier_ids.length||!c.orders_connected))throw new Fault('Сначала подключите бота заказов и укажите кассира.',400);return c;}
export async function admin(req,env){const t=cookie(req,'dtr_admin');if(!/^[a-f0-9]{64}$/.test(t))throw new Fault('Войдите в управление.',401);const row=await query(env,'SELECT expires FROM sessions WHERE hash=?',await sha(t)).first();if(!row||row.expires<now())throw new Fault('Войдите в управление снова.',401);return {type:'staff',id:'admin',name:'Администратор',can_pay:true,manager:true};}
export async function body(req){if(!req.headers.get('content-type')?.startsWith('application/json'))throw new Fault('Ожидается JSON.',415);const source=await req.text();if(source.length>150000)throw new Fault('Слишком большой запрос.',413);let p;try{p=JSON.parse(source);}catch{throw new Fault('Неверный JSON.',400);}if(!p||Array.isArray(p)||typeof p!=='object')throw new Fault('Неверный запрос.',400);return p;}
export function guard(req){const u=new URL(req.url);if(u.protocol!=='https:'&&!['localhost','127.0.0.1','[::1]'].includes(u.hostname))throw new Fault('Для заказов требуется HTTPS.',403);const o=req.headers.get('origin');if(o&&o!==u.origin)throw new Fault('Запрос с другого сайта запрещён.',403);if(req.headers.get('sec-fetch-site')==='cross-site')throw new Fault('Запрос с другого сайта запрещён.',403);}
