import {Fault,now,token,uid,sha,sign,equal,text,query,config,cookie,rate} from './core.js';
export async function table(env,id){if(!Number.isSafeInteger(id)||id<1)throw new Fault('Отсканируйте QR на столе.',404);const t=await query(env,'SELECT * FROM dining_tables WHERE id=?',id).first();if(!t)throw new Fault('Стол не найден.',404);return t;}
export async function row(env,id){if(typeof id!=='string'||!/^[a-f0-9-]{36}$/.test(id))throw new Fault('Визит не найден.',404);const r=await query(env,'SELECT * FROM visits WHERE id=?',id).first();if(!r)throw new Fault('Визит не найден.',404);return {...r,data:JSON.parse(r.state)};}
export async function write(env,r,s){const pending=s.jobs.some(j=>j.status==='queued')?1:0;const res=await query(env,'UPDATE visits SET state=?,status=?,version=version+1,pending=? WHERE id=? AND version=?',JSON.stringify(s),s.status,pending,r.id,r.version).run();if(res.meta.changes!==1)throw new Fault('Счёт изменился. Обновите страницу и повторите действие.');}
export function totals(s){const subtotal=s.orders.filter(o=>o.status!=='cancelled').reduce((a,o)=>a+o.items.reduce((n,l)=>n+l.price*l.quantity,0),0);const service=Math.floor((subtotal*s.service_bps+5000)/10000);return {subtotal,service,total:subtotal+service};}
export async function view(env,s,staff=false){const c=await config(env);const {join_hash,guests,jobs,audit,...safe}=structuredClone(s);safe.orders=safe.orders.map(({key,fingerprint,...o})=>({...o,notification:jobs.find(j=>j.key==='order:'+o.id)?.status||'queued'}));safe.totals=totals(s);safe.kaspi_url=s.status==='payment_pending'?c.kaspi_url:'';if(!staff)delete safe.paid_by;if(s.closed_at&&now()<=s.closed_at+604800)safe.review_token=await sign(env,'review:'+s.id);return safe;}
export function audit(s,actor,action){s.audit.push({at:now(),actor:actor.id,action});if(s.audit.length>350)s.audit=s.audit.slice(-350);}
export function queue(s,key,kind,channel='orders',extra={}){if(s.jobs.some(j=>j.key===key))return;s.jobs.push({key,kind,channel,...extra,status:'queued',attempts:0,available_at:now(),error:''});}
export async function open(env,id,actor){const t=await table(env,id),c=await config(env),v=uid(),code=String(100000+(crypto.getRandomValues(new Uint32Array(1))[0]%900000));const s={id:v,table_id:id,table_name:t.name,status:'open',opened_at:now(),expires_at:now()+c.hours*3600,closed_at:0,service_bps:c.service_bps,join_hash:await sign(env,v+':'+code),join_until:now()+900,guests:[],orders:[],invoice:null,review:null,paid_by:null,jobs:[],audit:[]};audit(s,actor,'open');try{await query(env,'INSERT INTO visits(id,table_id,status,state,created_at) VALUES (?,?,?,?,?)',v,id,'open',JSON.stringify(s),now()).run();}catch(e){if(String(e.message).includes('UNIQUE'))throw new Fault('Стол уже открыт. Используйте «Новый код».');throw e;}return {visit:await view(env,s,true),code};}
export async function join(req,env,p){const id=Number(p.table);await rate(env,'joinip:'+req.headers.get('cf-connecting-ip'),40,600);await rate(env,'jointable:'+id,30,600);await table(env,id);const active=await query(env,"SELECT id FROM visits WHERE table_id=? AND status!='closed'",id).first();if(!active)throw new Fault('Попросите официанта открыть стол.',403);const r=await row(env,active.id),s=r.data;if(!/^\d{6}$/.test(p.code)||s.status!=='open'||s.expires_at<=now()||s.join_until<=now()||!equal(s.join_hash,await sign(env,s.id+':'+p.code)))throw new Fault('Код не действует. Уточните код у официанта.',403);if(s.guests.length>=30)throw new Fault('Попросите помощи официанта.',429);const t=token();s.guests.push(await sha(t));audit(s,{id:'guest'},'join');await write(env,r,s);return {token:s.id+'.'+t,state:await view(env,s)};}
export async function guest(req,env,id){const c=cookie(req,'dtr_g_'+id);if(!/^[a-f0-9-]{36}\.[a-f0-9]{64}$/.test(c))throw new Fault('Введите код от официанта.',401);const [vid,t]=c.split('.'),r=await row(env,vid);if(r.data.table_id!==id||!r.data.guests.includes(await sha(t)))throw new Fault('Доступ недействителен.',403);if(r.data.closed_at&&now()>r.data.closed_at+604800)throw new Fault('Срок доступа истёк.',410);return r;}
export async function change(env,id,action,p,actor){const r=await row(env,id),s=r.data,t=now();let event=null;const isGuest=actor.type==='guest';if(isGuest&&!['order','request_payment','review','help'].includes(action))throw new Fault('Недостаточно прав.',403);
if(action==='order'){
if(s.status==='closed'||s.expires_at<=t)throw new Fault('Доступ к заказам завершён. Обратитесь к официанту.',410);if(s.status!=='open')throw new Fault('Счёт готовится к оплате. Попросите официанта разрешить дозаказ.');if(typeof p.key!=='string'||!/^[a-zA-Z0-9_-]{16,80}$/.test(p.key))throw new Fault('Не удалось проверить заказ.',400);if(!Array.isArray(p.items)||!p.items.length||p.items.length>60)throw new Fault('Добавьте блюда.',400);const seen=new Set(),items=p.items.map(i=>{if(!i||!Number.isInteger(i.id)||seen.has(i.id)||!Number.isInteger(i.quantity)||i.quantity<1||i.quantity>20)throw new Fault('Проверьте количество блюд.',400);seen.add(i.id);return {id:i.id,quantity:i.quantity};}).sort((a,b)=>a.id-b.id);const note=text(p.note??'',300),fp=await sha(JSON.stringify([items,note])),dup=s.orders.find(o=>o.key===p.key);if(dup){if(dup.fingerprint!==fp)throw new Fault('Этот запрос уже использован для другого заказа.');return view(env,s);}if(s.orders.length>=40)throw new Fault('Следующий заказ примет официант.',429);if(s.orders.length&&t-s.orders.at(-1).at<3)throw new Fault('Подождите несколько секунд.',429);const c=await config(env);if(!c.enabled)throw new Fault('Онлайн-заказы отключены.',503);const lines=items.map(i=>{const d=c.items.find(d=>d.id===i.id&&d.available);if(!d)throw new Fault('Некоторых блюд сейчас нет. Обновите меню.');return {id:d.id,name:d.name,price:d.price,quantity:i.quantity};});const o={id:token(6),number:s.orders.length+1,key:p.key,fingerprint:fp,items:lines,note,status:'new',at:t,waiter:null};s.orders.push(o);queue(s,'order:'+o.id,'order','orders',{order_id:o.id});
}else if(action==='request_payment'){
if(s.status==='closed')throw new Fault('Счёт уже закрыт.',410);if(s.status==='payment_pending')return view(env,s);if(s.orders.some(o=>o.status==='new'))throw new Fault('Дождитесь подтверждения всех заказов.');const total=totals(s).total;if(!total)throw new Fault('В счёте пока нет принятых блюд.');s.status='payment_pending';s.invoice={id:token(8),total,at:t};event={kind:'payment',invoice_id:s.invoice.id};
}else if(['accept','reject','arrived','served'].includes(action)){
if(s.status==='closed')throw new Fault('Счёт уже закрыт.');const o=s.orders.find(o=>o.id===p.order_id);if(!o)throw new Fault('Заказ не найден.',404);const target={accept:'accepted',reject:'cancelled',arrived:'arrived',served:'served'}[action];if(o.status===target)return view(env,s,true);if(['accept','reject'].includes(action)){if(s.status!=='open'||o.status!=='new')throw new Fault('Заказ уже обработан.');o.waiter={id:actor.id,name:actor.name};}else{if(!['accepted','arrived'].includes(o.status))throw new Fault('Сначала примите заказ.');if(o.waiter?.id!==actor.id&&!actor.manager)throw new Fault('Заказ закреплён за другим официантом.',403);}o.status=target;event={kind:'status',order_id:o.id};
}else if(action==='confirm_payment'){
if(!actor.can_pay)throw new Fault('Оплату подтверждает кассир.',403);if(s.status==='closed'&&s.invoice?.id===p.invoice_id)return view(env,s,true);if(s.status!=='payment_pending'||s.invoice.id!==p.invoice_id)throw new Fault('Счёт изменился. Используйте актуальное подтверждение.');if(p.verified!==true||p.amount!==s.invoice.total)throw new Fault('Проверьте поступление полной суммы.',400);s.status='closed';s.closed_at=t;s.paid_by={id:actor.id,name:actor.name};event={kind:'closed'};
}else if(action==='resume'){
if(s.status!=='payment_pending')throw new Fault('Счёт не ожидает оплаты.');s.status='open';s.invoice=null;event={kind:'resumed'};
}else if(action==='code'||action==='extend'){
if(s.status==='closed')throw new Fault('Создайте новый визит. Старый завершён.',410);if(action==='code'){const code=String(100000+(crypto.getRandomValues(new Uint32Array(1))[0]%900000));s.join_hash=await sign(env,s.id+':'+code);s.join_until=t+900;audit(s,actor,action);await write(env,r,s);return {...await view(env,s,true),new_code:code};}s.expires_at=t+(await config(env)).hours*3600;
}else if(action==='close_empty'){
if(s.status==='closed')throw new Fault('Визит уже закрыт.');if(totals(s).total)throw new Fault('Сначала подтвердите оплату.');s.status='closed';s.closed_at=t;s.closed_empty=true;event={kind:'closed'};
}else if(action==='review'){
if(!s.closed_at||t>s.closed_at+604800||!equal(await sign(env,'review:'+s.id),p.token))throw new Fault('Ссылка отзыва недействительна.',403);if(s.review)throw new Fault('Спасибо, отзыв уже получен.');if(!Number.isInteger(p.rating)||p.rating<1||p.rating>5)throw new Fault('Выберите оценку от 1 до 5.',400);s.review={rating:p.rating,text:text(p.text??'',1000),at:t,case_status:'new'};const c=await config(env);if(p.rating<=3){queue(s,'review','review','admin');if(!c.admin_chat_id||!env.ADMIN_BOT_TOKEN)s.jobs.at(-1).error='Бот отзывов не настроен';}
}else if(action==='review_case'){
if(!actor.manager||!s.review)throw new Fault('Действие доступно администратору.',403);if(!['working','contacted','closed'].includes(p.case_status))throw new Fault('Неверный статус.',400);s.review.case_status=p.case_status;
}else if(action==='help'){
if(s.status==='closed')throw new Fault('Визит завершён.',410);if(s.last_help&&t-s.last_help<60)throw new Fault('Официант уже получил вызов. Подождите минуту.',429);s.last_help=t;event={kind:'help'};
}else if(action==='retry'){
if(!actor.manager)throw new Fault('Недостаточно прав.',403);for(const j of s.jobs)if(j.status==='dead'){j.status='queued';j.available_at=t;j.attempts=0;j.error='';}
}else throw new Fault('Неизвестное действие.',400);
if(event)queue(s,action+':'+r.version,event.kind,'orders',event);audit(s,actor,action);await write(env,r,s);return view(env,s,!isGuest);}
