import {Fault,now,token,sha,sign,equal,text,cookie,cookieValue,query,config,saveConfig,validateConfig,admin,body,guard,rate} from './core.js';
import {table,row,write,view,open,join,guest,change} from './service.js';
import {connect,receive,call,drain} from './telegram.js';
const guestActor={type:'guest',id:'guest'};
const headers={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store, private','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','X-Frame-Options':'DENY'};
const response=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{...headers,...extra}});
export async function route(req,env,ctx){const u=new URL(req.url),path=u.pathname;if(!path.startsWith('/api/'))return env.ASSETS.fetch(req);const local=['localhost','127.0.0.1','[::1]'].includes(u.hostname);env={...env,_mock:local&&env.LOCAL_DEMO==='1'};const method=req.method;try{if(!['GET','POST'].includes(method))throw new Fault('Метод недоступен.',405);if(path.startsWith('/api/telegram/')){if(method!=='POST')throw new Fault('Метод недоступен.',405);const ch=path.slice(14);if(!['orders','admin'].includes(ch))throw new Fault('Не найдено.',404);const result=await receive(req,env,await body(req),ch);ctx.waitUntil(drain(env).catch(()=>{}));return response(result);}if(method==='POST')guard(req);const p=method==='POST'?await body(req):Object.fromEntries(u.searchParams);const c=await config(env);let result,extra={};const id=Number(p.table||0);const wake=()=>ctx.waitUntil(drain(env).catch(()=>{}));
if(path==='/api/menu'&&method==='GET'){const t=id?await table(env,id):null;result={name:c.name,service_bps:c.service_bps,enabled:c.enabled,items:c.items,table:t,sample_menu:c.sample_menu,local_demo:env._mock};}
else if(path==='/api/join'&&method==='POST'){if(!c.enabled)throw new Fault('Онлайн-заказы пока отключены.',503);const j=await join(req,env,p);extra['Set-Cookie']=cookieValue(req,'dtr_g_'+id,j.token,604800);result=j.state;}
else if(path==='/api/visit'&&method==='GET'){result=await view(env,(await guest(req,env,id)).data);}
else if(['/api/order','/api/payment','/api/help'].includes(path)&&method==='POST'){const r=await guest(req,env,id);result=await change(env,r.id,{'/api/order':'order','/api/payment':'request_payment','/api/help':'help'}[path],p,guestActor);wake();}
else if(['/api/review','/api/review-info'].includes(path)&&method==='POST'){await rate(env,'review:'+req.headers.get('cf-connecting-ip'),40,600);const s=(await row(env,p.id)).data;if(!s.closed_at||now()>s.closed_at+604800||!equal(p.token,await sign(env,'review:'+s.id)))throw new Fault('Ссылка отзыва недействительна.',403);if(path==='/api/review'){await change(env,s.id,'review',p,guestActor);wake();}result={ok:true,reviewed:path==='/api/review'||!!s.review,table_name:s.table_name};}
else if(path==='/api/login'&&method==='POST'){await rate(env,'login:'+req.headers.get('cf-connecting-ip'),8,900);if(!env.ADMIN_PASSWORD||env.ADMIN_PASSWORD.length<20||!env.SESSION_SECRET||env.SESSION_SECRET.length<32)throw new Fault('Администратор ещё не настроен. Добавьте секреты при публикации.',503);const password=text(p.password,200);if(!equal(await sha(password),await sha(env.ADMIN_PASSWORD)))throw new Fault('Неверный пароль.',401);const t=token();await query(env,'INSERT INTO sessions(hash,expires) VALUES (?,?)',await sha(t),now()+43200).run();extra['Set-Cookie']=cookieValue(req,'dtr_admin',t,43200);result={ok:true};}
else if(path==='/api/logout'&&method==='POST'){const t=cookie(req,'dtr_admin');if(t)await query(env,'DELETE FROM sessions WHERE hash=?',await sha(t)).run();extra['Set-Cookie']=cookieValue(req,'dtr_admin','',0);result={ok:true};}
else if(path.startsWith('/api/admin')){const who=await admin(req,env);
if(path==='/api/admin'&&method==='GET'){const tables=await query(env,"SELECT t.*,v.id AS active_visit FROM dining_tables t LEFT JOIN visits v ON v.table_id=t.id AND v.status!='closed' ORDER BY t.id").all();const rows=await query(env,"SELECT * FROM visits ORDER BY (status='closed'),created_at DESC LIMIT 250").all();const visits=await Promise.all(rows.results.map(r=>view(env,JSON.parse(r.state),true)));result={config:c,tables:tables.results,visits,delivery:rows.results.flatMap(r=>JSON.parse(r.state).jobs.filter(j=>j.status==='dead').map(j=>({visit_id:r.id,key:j.key,error:j.error,channel:j.channel}))),secrets:{orders:!!env.ORDERS_BOT_TOKEN,admin:!!env.ADMIN_BOT_TOKEN},local_demo:env._mock};}
else if(path==='/api/admin/config'&&method==='POST'){if(p.version!==c.version)throw new Fault('Настройки изменились. Обновите страницу.');result=await saveConfig(env,validateConfig(p,c,env),c.version);}
else if(path==='/api/admin/table'&&method==='POST'){const name=text(p.name,80);if(!name)throw new Fault('Укажите название стола.',400);const count=await query(env,'SELECT COUNT(*) AS n FROM dining_tables').first();if(count.n>=150)throw new Fault('Достигнут лимит столов.',400);await query(env,'INSERT INTO dining_tables(name) VALUES (?)',name).run();result={ok:true};}
else if(path==='/api/admin/action'&&method==='POST'){if(!['open','accept','reject','arrived','served','confirm_payment','resume','code','extend','close_empty','review_case','retry'].includes(p.action))throw new Fault('Недоступное действие.',400);result=p.action==='open'?await open(env,id,who):await change(env,p.id,p.action,p,who);wake();}
else if(path==='/api/admin/connect'&&method==='POST'){result=await connect(req,env,p.channel);}
else if(path==='/api/admin/ids'&&method==='POST'){const r=await call(env,p.channel,'getUpdates',{limit:50,timeout:0});if(!r.ok)throw new Fault('Остановите старый обработчик. Получение ID работает до подключения webhook.',409);result={messages:r.result.filter(u=>u.message).map(u=>({chat_id:String(u.message.chat.id),title:u.message.chat.title||u.message.chat.type,user_id:String(u.message.from?.id||''),name:u.message.from?.first_name||''}))};}
else throw new Fault('Не найдено.',404);
}else throw new Fault('Не найдено.',404);
return response(result,200,extra);
}catch(e){if(e instanceof Fault)return response({message:e.message},e.status);return response({message:'Не удалось выполнить запрос. Повторите действие. Если ошибка сохраняется, обратитесь к администратору.'},503);}}
export default {fetch:route,async scheduled(event,env,ctx){ctx.waitUntil((async()=>{await drain(env);await env.DB.batch([query(env,'DELETE FROM limits WHERE expires<?',now()),query(env,'DELETE FROM sessions WHERE expires<?',now()),query(env,'DELETE FROM updates WHERE done=1 AND expires<?',now())]);})());}};
